### PR TITLE
test request 

### PR DESCRIPTION
**Pull request by laiyskylone**
basic structure project

### CODE REVIEW

**Comment by b0noI** [comment]
I have add comments, please made some changes and the code will be ready to be pulled in main repo

**Comment by laiyskylone** [comment]
1

**Comment by laiyskylone** [comment]
I apologize for my English because it is not a very high level
Yes, it's a big mistake but I saw her after the push (files of IDE)

thank you very much for a quick refactor code and detailed comments try to quickly fix mistakes...
but I will have a many of questions for your comments

**Comment by b0noI** [comment]
@laiyskylone feel free to post questions here and then we will share it with other students because I am sure that other people will have similar questions. 

BTW: you are doing awesome progress!

**Comment by laiyskylone** [comment]
I probably again push IDE files, although since I've only got classes,  files IDE not push. I think this could be something to do

BTW: guys probably do not know how to do so is not pull request. That's not who never sends. Although you are very good teacher and set out for all available (although I'm not a lot do not understand the lessons about memory and links) But I will see several times.

**Comment by laiyskylone** [comment]
Damn, this git...
==
I need a little more time to figure out how to remove files without breaking structure in IDA, because IDA or git swears

**Comment by laiyskylone** [comment]
seems all fix

**Comment by laiyskylone** [comment]
##### I want to ask about the rules for writing comments in the code?
* 27 lines of my comment is pressed to the method filtrValue
* to do '\n' between 27 and 28 lines

or any general rules of etiquette comments?

Image

**Comment by b0noI** [comment]
filterMethod is the method that shows line of characters (*** or $$$). Default value better also make some lines like ---.

So, name of this method should be different, something like:
printLine

In method comment you SHOULD NOT say where you calling this method from: 
//depending on the value displays characters _before showPlayersName_ and after the _showGamesName_

because this method might be called anywhere else.

Also static variables named in nit very good way:
ZERO_VALUE_FILTER_SWITCH - this name shows what integers inside this variable (ZERO_VALUE) and where you going to use it (FILTER_SWITCH) and NOTHING about real meaning of this variable. Good name could be something like LINE_WITH_STARS, in this case if someone calls your method call will be like this:

printLine(LINE_WITH_STARS); // this is readable code that shows everything that user need to understand what this method will do

filterMethod(ZERO_VALUE_FILTER_SWITCH); // this is not readable code that need comment to understand what this code actually doing

Also if you want to make printLine method more safer it could be like:

printLine(final Character lineCharacter) {
...
}

in this case it could print line with ANY character that customer needs like this:

printLine('*'); // will print ***

or

printLine('$'); // will print $$$

or maybe even better method could be like this:

printLine(final Character lineCharacter, final int line size) {
...
}

and call examples:

printLine('*', 5); // will print *****

or

printLine('%', 8); // will print %%%%%%%%

so please refactor this method, at least rename it and constants to something more readable. And remove the comment we do not need it there after renaming.

**Comment by b0noI** [comment]
this pullRequest merged already so all other changes need to be done in other pullRequest

**Comment by laiyskylone** [comment]
try to make or edit the names of the constants

**Comment by laiyskylone** [comment]
Thx for the detailed explanation I will try to rewrite the method if I can in
the next 1-2days
Because it can not seem to figure out how to do that would be an asterisk (*
) increased the number of which takes lineSize I think to use an array

2015-02-08 14:08 GMT+02:00 b0noI <notifications@github.com>:

**Comment by b0noI** [comment]
@laiyskylone for printLine method with size you can loop. However for now, maybe, you can implement just printLine with Character in input

**Comment by laiyskylone** [comment]
like I did through the cycle but the output symbols in a column instead of
a string

I'll think about how to do it and if you will push

2015-02-08 21:36 GMT+02:00 b0noI <notifications@github.com>:

**Comment by b0noI** [comment]
try using 
print()
instead of
println()

;)

**Comment by laiyskylone** [comment]
OMG... this is a big mistake
I spent the whole day (10 hours) that would deal with arrays and do because
I do not know about print()


2015-02-09 2:12 GMT+02:00 b0noI <notifications@github.com>:

**Comment by b0noI** [comment]
@laiyskylone happens =) tasks like this when you investigating problem with 1 line solution for 2 days happens offten =) (not joking)

**Pull request merged**
